# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170530_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secs',
            fields=[
                ('sec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sec_name', models.CharField(max_length=50, unique=True, verbose_name='券商名称')),
                ('gqj_data', models.CharField(max_length=50, verbose_name='成交额(亿)')),
                ('gqj_rank', models.IntegerField(verbose_name='名次')),
            ],
        ),
    ]
