# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_secs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secs',
            name='sec_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
