# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170530_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secs',
            name='sec_name',
            field=models.CharField(max_length=50, verbose_name='券商名称'),
        ),
    ]
